project:
  type: website
  resources:
    - "images/twitter-card.png"
  render:
    - "*.qmd"
    - "!materials/exercises"

website:
  page-navigation: true
  title: "Shiny web applications"
  description: "Homepage for WOMBAT 2022 workshop"
  site-url: "#"
  
  repo-url: https://github.com/mitchelloharawild/shiny-basics
  repo-actions: [edit, issue]

  # opengraph: true
  twitter-card:
    creator: "@mitchoharawild"
    image: "/images/twitter-card.png"

  favicon: "/images/shiny.svg"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2022, Mitchell O'Hara-Wild"
    background: "#60A2DF"

  navbar:
    background: "#60A2DF"
    logo: "images/shiny.svg"
    pinned: true
    align: center
    right:
      - icon: download
        text: Downloads
        menu: 
          - text: All Course Materials
            href: ggplot2-course-material.zip
          - text: Data Sets
            href: ggplot2-course-data.zip
      - icon: file-certificate
        href: license.qmd
      - icon: github
        href: https://github.com/mitchelloharawild/shiny-basics
        text: GitHub
    left:
      - text: Sessions
        menu: 
          - text: Basics of Shiny
            href: sessions/01_basics.qmd
          - text: Reactive programming
            href: sessions/02_reactive.qmd
          - text: Publishing apps
            href: sessions/03_publish.qmd
      - href: schedule.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Open Sans"

