project:
  type: website
  resources:
    - "images/twitter-card.png"
    - "materials"
  render:
    - "*.qmd"
    - "!materials"
    - "!README.Rmd"

website:
  page-navigation: true
  title: "Shiny web applications"
  description: "Homepage for WOMBAT 2022 workshop"
  site-url: "https://workshop.mitchelloharawild.com/shiny-basics"
  
  repo-url: https://github.com/mitchelloharawild/shiny-basics
  repo-actions: [edit, issue]

  # opengraph: true
  twitter-card:
    creator: "@mitchoharawild"
    image: "/images/twitter-card.png"

  favicon: "/images/shiny.svg"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2022, Mitchell O'Hara-Wild"
    background: "#60A2DF"

  navbar:
    background: "#60A2DF"
    logo: "images/shiny.svg"
    pinned: true
    align: center
    right:
      - icon: download
        text: Downloads
        menu: 
          - text: Everything! Including this website!
            href: 'https://github.com/mitchelloharawild/shiny-basics/archive/refs/heads/main.zip'
          - text: All Course Materials
            href: '#'
          - text: Demonstrated Shiny Applications
            href: '#'
      - icon: file-certificate
        href: license.qmd
      - icon: github
        href: https://github.com/mitchelloharawild/shiny-basics
    left:
      - text: Sessions
        menu: 
          - text: Basics of Shiny
            href: sessions/01_basics.qmd
          - text: Reactive programming
            href: sessions/02_reactive.qmd
          - text: Publishing apps
            href: sessions/03_publish.qmd
      - href: schedule.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Open Sans"
    include-after-body: plausible.html
